### ISSUE TITLE
Manche Felder werden in Childlayouts beim Speichern wieder überschrieben

### ISSUE THREAD

**Issue by Kahmoon** [richardhj/contao-childlayouts#3]
Hi,

mir ist gerade in Fehler bei Childlayouts unter Contao 3.4.5 aufgefallen.

Ich habe ein Childlayout erstellt, bei dem der Header eine andere Höhe hat. Das ignoriert er. Sobald ich speichere steht der Wert des Elternlayouts(100px) drin statt 68px vom Child.

Hier auch mein Beitrag im Forum: http://bit.ly/1JJJ75r

VG
Frank

**Comment by richardhj** [comment]
Hallo,

bitte jetzt noch mal testen. Vielen Dank.

Fixed in 98d939c33f3eedbe4e24a5361d460c6946bbf1f2

**Comment by Kahmoon** [comment]
Hmm ich hab im ER kein Update bekommen!? Muss ich das manuell machen?
