### ISSUE TITLE
Umgewandeltes Childlayout behält Einstellung aus Masterlayout

### ISSUE THREAD

**Issue by Kahmoon** [richardhj/contao-childlayouts#4]
Hi,

wenn ich ein kopiertes Layout, das bereits eigene Einträge im Headbereich hatte, in ein Childlayout umwandle und den Bereich Erweitert (enthält head) nicht auswähle, dann nimmt er nicht die Einstellungen vom Master sondern von seiner vorherigen Version. Auch wenn ich alles rauslösche und speichere, entfernt er es nicht sobald es wieder ein Child wird.

Das passiert sowohl in Contao 3.1.2 als auch in 3.4.5

Hier auch mein Beitrag im Forum: http://bit.ly/1JJJfSv

VG
Frank

**Comment by richardhj** [comment]
Ist dieses Problem nun auch durch den letzten Commit gelöst? Und wenn nicht, dann konnte ich das Problem leider nicht nachvollziehen.
