### ISSUE TITLE
Reihenfolge Externe Stylesheets geht verloren

### ISSUE THREAD

**Issue by manjarco** [richardhj/contao-childlayouts#5]
Fügt man in einem Kind-Layout externe css-Dateien hinzu und sortiert sie manuell um werden diese nach dem Speichern des Layouts wieder alphabetisch geladen. Gerade ungut wenn dann base.css vor reset.css steht.

(Workaround mit Nummerierung der css-Dateien ist ja einfach, könnte bei unerfahrenen Nutzern aber zu Verwirrung führen.)

**Comment by richardhj** [comment]
Bei den `fileTree`-Feldern wird das zugehörige ```eval => ['orderField' => '']``` nicht berücksichtigt.
Ich veröffentliche einen Fix asap.
Vielen Dank und beste Grüße!
