### ISSUE TITLE
Update für Contao 4.4

### ISSUE THREAD

**Issue by websolutions-hamburg** [richardhj/contao-childlayouts#6]
Hallo,

ist eine Anpassung für Contao 4.4 möglich oder sogar schon in Planung?

**Comment by fritzmg** [comment]
Have you tried the extension in Contao 4 yet?

**Comment by fritzmg** [comment]
Just in case you do not know how to manually install this extension (in Contao 3 or 4):

1. download the zip archive from GitHub
2. extract the `contao` folder of the extension to `system/modules` of your Contao installation
3. rename the folder to `childlayouts`
4. open the Install Tool to update the database

**Comment by websolutions-hamburg** [comment]
It seems to work with the manual installation way. Thanks for the instructions @fritzmg.

So maybe it is better to ask: It it possible to update `composer.json` and the install process so it will work with contao 4 and composer and the contao manager?

**Comment by fritzmg** [comment]
See #7 ;)

**Comment by richardhj** [comment]
Thank you @fritzmg. You might want to use the composer from now @websolutions-hamburg

**Comment by fritzmg** [comment]
@websolutions-hamburg be advised, that when you first manually deinstall the manually installed extension, you also need to manually delete `var/cache/prod`.
