### ISSUE TITLE
Backend Design Fehler 

### ISSUE THREAD

**Issue by websolutions-hamburg** [richardhj/contao-childlayouts#8]
Hallo,

im Backend wird die Auswahlbox **Kind-Layout** unter Contao 4.4.4 nicht richtig dargestellt. Ich konnte den Fehler durch folgende Anpassung der CSS Klassen korrigieren:

```php
$GLOBALS['TL_DCA']['tl_layout']['fields']['isChild']['eval']['tl_class'] = 'w50 m12';
```

**Comment by richardhj** [comment]
For some reason, I don't find a solution for both Contao 3 and 4 at first go.

![](https://i.imgur.com/Q3cUg29.gif)

But I'll keep trying.

**Comment by websolutions-hamburg** [comment]
Ah I see, maybe this will help you:

```php
$GLOBALS['TL_DCA']['tl_layout']['fields']['isChild']['eval']['tl_class'] = (int)VERSION > 3 ? 'w50 m12' : 'long';
```
